// Helper to generate a unique ID
function uuid() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function(c) {
        const r = Math.random() * 16 | 0, v = c === 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
    });
}

// Get all events from localStorage
async function getEvents() {
    const snapshot = await db.collection('events').get();
    const events = [];
    snapshot.forEach(doc => {
        events.push({ id: doc.id, ...doc.data() });
    });
    return events;
}

// Save all events to localStorage
async function createEvent(eventData) {
    // Ensure a description field exists, even if empty, to match the data model.
    const completeEventData = { ...eventData, description: eventData.description || '' };

    // The 'id' will be auto-generated by Firestore's add() method.
    const docRef = await db.collection('events').add(completeEventData);
    return docRef.id;
}

// Update an existing event in Firestore
async function updateEvent(eventId, eventData) {
    const eventRef = db.collection('events').doc(eventId);
    await eventRef.update(eventData);
}

// Get a single event by its ID
async function getEventById(eventId) {
    const doc = await db.collection('events').doc(eventId).get();
    return doc.exists ? { id: doc.id, ...doc.data() } : null;
}

// Get tickets for a specific event (alias for getAttendees)
async function getTicketsForEvent(eventId) {
    const snapshot = await db.collection('tickets').where('eventId', '==', eventId).get();
    const tickets = [];
    snapshot.forEach(doc => {
        tickets.push({ id: doc.id, ...doc.data() });
    });
    return tickets;
}

// Helper to get all tickets from localStorage
async function getAllTickets() {
    const snapshot = await db.collection('tickets').get();
    const tickets = [];
    snapshot.forEach(doc => {
        tickets.push({ id: doc.id, ...doc.data() });
    });
    return tickets;
}

// Helper to save all tickets to localStorage
function saveAllTickets(tickets) {
    // This function is now obsolete with Firestore, but can be kept for reference or removed.
    console.warn("saveAllTickets is deprecated. Use saveAttendee instead.");
}

// Get attendees for a specific event (now an alias for getTicketsForEvent)
async function getAttendees(eventId) {
    return getTicketsForEvent(eventId);
}

// Save a new attendee/ticket.
async function saveAttendee(eventId, newAttendee) {
    // The newAttendee object already contains the ticket ID.
    // We will use that as the document ID in Firestore.
    const ticketRef = db.collection('tickets').doc(newAttendee.id);
    await ticketRef.set({ ...newAttendee, eventId: eventId });
}

// Function to clear all registered tickets from Firestore
async function deleteAllTickets() {
    if (confirm('Are you sure you want to delete ALL ticket data? This cannot be undone.')) {
        const snapshot = await db.collection('tickets').get();
        const batch = db.batch();
        snapshot.docs.forEach(doc => {
            batch.delete(doc.ref);
        });
        await batch.commit();
        alert('All ticket data has been deleted.');
    }
}

// --- ONE-TIME DATA SEEDING ---
// This function uploads the initial data from events-data.js to Firestore.
// It should only be run once to avoid creating duplicate data.
// It uses .set() so it will overwrite existing data with the same ID.
async function seedInitialDataToFirestore() {
    if (!confirm("Are you sure you want to seed the initial data? This will upload all events and tickets from events-data.js, overwriting any existing data with the same IDs.")) {
        return;
    }

    console.log("Starting to seed data...");
    const { events, tickets } = getInitialData();
    const batch = db.batch();

    // Add events to the batch. Using the event.id as the document ID.
    events.forEach(event => {
        const eventRef = db.collection('events').doc(event.id);
        batch.set(eventRef, event);
    });

    // Add tickets to the batch. Using the ticket.id as the document ID.
    tickets.forEach(ticket => {
        const ticketRef = db.collection('tickets').doc(ticket.id);
        batch.set(ticketRef, ticket);
    });

    // Commit the batch
    await batch.commit();
    console.log("Successfully seeded events and tickets to Firestore!");
    alert("Initial events and tickets have been uploaded to the database. Please refresh the page.");
}